import json
from typing import Dict, Any

from app.services.llm_service import call_llm


def prepare_manual_prompt(payload: Dict[str, Any]) -> str:
    pretty_json = json.dumps(payload, indent=2, ensure_ascii=False)

    return f"""
Ты — Senior QA Engineer, который пишет manual-тесты в формате
Allure TestOps as Code (Python).

Ниже — структурированная информация об API-эндпоинте:

--- BEGIN ENDPOINT JSON ---
{pretty_json}
--- END ENDPOINT JSON ---

Твоя задача — сгенерировать ручной тест-кейс (manual test)
в формате Python, совместимый с Allure TestOps.

‼ ТРЕБОВАНИЯ:

1. Выводи ТОЛЬКО Python-код.
2. Без Markdown и без ```python.
3. Используй импорты:
    import allure
    from pytest import mark

4. Формат теста:
@allure.manual
@allure.feature("<раздел, например VMs>")
@allure.story("<краткое описание операции>")
@allure.suite("manual")
@mark.manual
class Test<Имя>Manual:
    @allure.title("<человекочитаемый заголовок>")
    @allure.tag("POSITIVE")
    @allure.label("priority", "high")
    def test_manual(self):
        with allure.step("Arrange: ..."):
            pass
        with allure.step("Act: ..."):
            pass
        with allure.step("Assert: ..."):
            pass

5. AAA-паттерн обязателен.
6. Ориентируйся на fields/request/response из payload.
7. Если в path есть UUID-параметры — упомяни это в Arrange.
8. Название теста должно отражать operation_id или summary.

Сгенерируй корректный manual-тест.
"""


def generate_api_manual_test(payload: Dict[str, Any]) -> str:
    prompt = prepare_manual_prompt(payload)
    code = call_llm(prompt)
    return code.strip()


def compose_manual_test_file(test_name: str, tests_code: str) -> str:
    return f"""
# This manual test case was autogenerated by TestOps LLM Agent
# Endpoint: {test_name}

{tests_code}
"""
