import json
from typing import Dict, Any

from app.services.llm_service import call_llm


def prepare_prompt(payload: Dict[str, Any]) -> str:
    pretty_json = json.dumps(payload, indent=2, ensure_ascii=False)

    return f"""
Ты — Senior QA Automation Engineer. 
Твоя задача — сгенерировать корректный Python-код автотестов на pytest,
который проверяет API-эндпоинт по следующей структурированной информации:

--- BEGIN ENDPOINT JSON ---
{pretty_json}
--- END ENDPOINT JSON ---

‼ОБЯЗАТЕЛЬНЫЕ ТРЕБОВАНИЯ:

1. Выводи ТОЛЬКО Python-код, без Markdown и без ```python.
2. Тесты должны быть полностью самодостаточными, запускаться как есть.

3. Используй httpx (синхронный).
   import httpx
   import pytest
   import re

4. Используй AAA-паттерн:
   - Arrange: подготовка данных
   - Act: выполнение запроса
   - Assert: проверки

5. Всегда добавляй фикстуру:
    @pytest.fixture
    def auth_header():
        return {{"Authorization": "Bearer TEST_TOKEN"}}

6. Позитивный тест:
    - test_<operation_id>_success
    - проверка status_code == 200 или другой успешный код
    - проверка структуры response_schema
    - uuid поля — проверять через regex
    - enum поля — assert value in [...]

7. Негативный тест: invalid UUID
    Генерируется ТОЛЬКО если payload["uuid_path_params"] не пустой.
    - test_<operation_id>_invalid_uuid
    - подставить некорректный uuid в path
    - assert response.status_code == 400 или 422
    - если есть error_schemas["400"] — проверить структуру ошибки по схеме

8. Негативный тест: 404 Not Found
    Генерируется, если payload["negative_cases"]["supports_404"] == true.
    - test_<operation_id>_not_found
    - подставить корректный uuid, но несуществующий
    - assert response.status_code == 404
    - проверить структуру ошибки, если есть error_schemas["404"]

9. ExceptionSchema:
    Если payload["error_schemas"] содержит схемы ошибок:
        - сгенерируй тесты для каждого статус-кода в error_schemas
        - проверяй структуру ошибки:
            * message — обязательная строка
            * code — обязательная строка
            * details — опционально
        - assert isinstance(value, str)

10. Код должен быть валидным, компилироваться и полностью соответствовать данным из payload.

Сгенерируй итоговый Python-код автотестов для данного API.
"""


def generate_api_test(payload: Dict[str, Any]) -> str:
    """
    Вызывает LLM для генерации pytest кода.
    """
    prompt = prepare_prompt(payload)
    code = call_llm(prompt)

    return code.strip()


def compose_test_file(test_name: str, tests_code: str) -> str:
    """
    Собирает итоговый .py файл для эндпоинта.
    """
    return f"""
# This file was autogenerated by TestOps LLM Agent
# Endpoint: {test_name}

{tests_code}
"""